### ISSUE TITLE
Section 2 Task 1 lists a non-existent class

### ISSUE THREAD

**Issue by frosemond** [TTS-Curriculum/css-assignment#2]
Assignment definition
/* Task 1: Inline-block
- Change the display property of the **li items with class .inline-block** to "inline-block". 
- Give it 5px of padding as well to space them out
*/

There are no items in index.html with the class .inline-block

The correction below will resolve the issue:

/* Task 1: Inline-block
- Change the display property of the li items with class .favorite-food to "inline-block". 
- Give it 5px of padding as well to space them out
*/

**Comment by EthanAmato** [comment]
Amended the readme.md to say .favorite-food instead of .inline-block. Thank you for the catch!
